// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/ryan-pip/terraform-provider-airbyte/internal/sdk/pkg/models/shared"
	"net/http"
)

type CancelJobRequest struct {
	JobID int64 `pathParam:"style=simple,explode=false,name=jobId"`
}

type CancelJobResponse struct {
	ContentType string
	// Cancel a Job.
	JobResponse *shared.JobResponse
	StatusCode  int
	RawResponse *http.Response
}
