// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/ryan-pip/terraform-provider-airbyte/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateConnectionResponse struct {
	// Successful operation
	ConnectionResponse *shared.ConnectionResponse
	ContentType        string
	StatusCode         int
	RawResponse        *http.Response
}
