// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/ryan-pip/terraform-provider-airbyte/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetWorkspaceRequest struct {
	WorkspaceID string `pathParam:"style=simple,explode=false,name=workspaceId"`
}

type GetWorkspaceResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Get a Workspace by the id in the path.
	WorkspaceResponse *shared.WorkspaceResponse
}
