// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/ryan-pip/terraform-provider-airbyte/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateWorkspaceRequest struct {
	WorkspaceUpdateRequest shared.WorkspaceUpdateRequest `request:"mediaType=application/json"`
	WorkspaceID            string                        `pathParam:"style=simple,explode=false,name=workspaceId"`
}

type UpdateWorkspaceResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful operation
	WorkspaceResponse *shared.WorkspaceResponse
}
